### ISSUE TITLE
Face not detected! Ensure the video contains a face 

### ISSUE THREAD

**Issue by jon1301** [ajay-sainy/Wav2Lip-GFPGAN#28]
```
python inference.py --checkpoint_path checkpoints/wav2lip.pth --face /root/Wav2Lip-GFPGAN/inputs/girl.mp4 --audio /root/Wav2Lip-GFPGAN/inputs/girl.mp3  --outfile /root/Wav2Lip-GFPGAN/outputs/girl.mp4

100%|███████████████████████████████████████████████████████████████████████████████████| 84/84 [36:44<00:00, 26.24s/it]
  0%|                                                                                            | 0/22 [36:44<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 249, in main
    for i, (img_batch, mel_batch, frames, coords) in enumerate(tqdm(gen, 
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "inference.py", line 113, in datagen
    face_det_results = face_detect(frames) # BGR2RGB for CNN face detection
  File "inference.py", line 92, in face_detect
    raise ValueError('Face not detected! Ensure the video contains a face in all the frames.')
ValueError: Face not detected! Ensure the video contains a face in all the frames.
```

我的视频有人脸啊，而且一直是这个女的在说话，例如下图

![image](https://github.com/ajay-sainy/Wav2Lip-GFPGAN/assets/4018406/25e6ae3b-f76d-465c-9d28-782da1a35410)

**Comment by jon1301** [comment]
找到原因了，wav2lip.pth没有完全复制过去，就执行了
